services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    # Configuración de la base de datos
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: user-task
      MYSQL_USER: user-task
      MYSQL_PASSWORD: 2021
    volumes:
      - mysql_data:/data/db
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data: